[package]
name = "spacetimedb-core"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "spacetimedb"   # The name of the target.
path = "src/lib.rs"    # The source file of the target.

# Benching off, because of https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
bench = false

[[bench]]
name = "transactional_odb_bench"
harness = false

[[bench]]
name = "odb_flavor_bench"
harness = false

[dependencies] 
tokio = { version = "1.2", features = ["full"] }
wasmer = "3.0.1"
wasmer-middlewares = "3.0.1"
sha3 = "0.10.0"
hex = "0.4.3"
prost = "0.10"
lazy_static = "1.4.0"
# wasmer-compiler-llvm = "2.2.1"
spacetimedb-lib = { path = "../spacetimedb-lib" }
log = "0.4.16"
gotham = "0.7.1"
gotham_derive = "0.7"
hyper = "0.14.18"
log4rs = { version = "1.0.0", features = ["background_rotation", "rolling_file_appender", "compound_policy", "size_trigger", "fixed_window_roller"] }
serde = "1.0.136"
serde_json = { version = "1.0", features = ["raw_value"] }
anyhow = { version = "1.0.57", features = ["backtrace"] }
thiserror = "1.0.37"
jsonwebtoken = { version = "8.1.0" }
sha1 = "0.10.1"
base64 = "0.13.0"
tokio-tungstenite = "*"
regex = "1"
futures = "0.3"
prometheus = "0.13.0"
hostname = "^0.3"
clap = { version = "4.0.18", features = ["derive"] }
sled = "0.34.7"
email_address = "0.2.3"
sqlparser = "0.21.0"
backtrace = "0.3.66"
# pprof = { version = "0.10", features = ["flamegraph"] }
# perf_monitor = "0.2"
urlencoding = "2.1.2"
fs2 = "0.4.3"
once_cell = "1.16"

slab = "0.4.7"

# gluesql = "0.10"
bytes = "1.2.0" # TODO(rdaum): there's also a copy/fork of this inside prost. hmph.
strum = { version = "0.24.1", features = ["derive"] }
scopeguard = "1.1.0"
parking_lot = "0.12.1"
uuid = { version = "1.2.1", features = ["v4"]}

# Used for tracelog
imara-diff = "0.1.3"
tempdir = "0.3.7"
flate2 = "1.0.24"
wasmparser = "0.92.0"

# Rocksdb ostorage backend, linked only if "rocksdb" feature enabled.
[dependencies.rocksdb]
version = "0.19.0"
default-features = false
optional = true
features = ["lz4"] # if we link bzip, we get multiple defs

[features]
# Optional storage engines.
odb_rocksdb = ["dep:rocksdb"]
odb_sled = []
tracelogging = []

[dev-dependencies]
rusqlite = {version = "0.28.0", features = ["bundled"]}
criterion = { version = "0.4.0", features = ["async", "async_tokio", "html_reports"] }
rand = "0.8.5"

[build-dependencies]
prost-build = { version = "0.10" }
