[workspace]
members = [
  "crates/spacetimedb-lib",
  "crates/spacetimedb-core",
  "crates/spacetimedb-bindings-sys",
  "crates/spacetimedb-bindings",
  "crates/spacetimedb-bench",
  "crates/spacetimedb-bindings-macro",
  "crates/spacetimedb-cli",
  "crates/rust-wasm-test",
]
default-members = ["crates/spacetimedb-cli"]

[profile.release]
opt-level = 's'
lto = true
debug = true

[profile.dev]
opt-level = 2

[profile.bench]
debug = true