[workspace]
members = [
  "crates/spacetimedb-standalone",
  "crates/spacetimedb-cloud",
  "crates/spacetimedb-lib",
  "crates/spacetimedb-core",
  "crates/spacetimedb-bindings-sys",
  "crates/spacetimedb-bindings",
  "crates/spacetimedb-bench",
  "crates/spacetimedb-bindings-macro",
  "crates/spacetimedb-cli",
  "crates/spacetimedb-sats",
  "crates/rust-wasm-test",
  "crates/spacetimedb-replay",
  "crates/spacetimedb-client-api",
]
default-members = ["crates/spacetimedb-cli"]

[profile.release]
opt-level = 's'
lto = true
debug = true

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
rpath = false

[profile.bench]
debug = true
