[workspace]
members = [
  "crates/spacetimedb-lib",
  "crates/spacetimedb-core",
  "crates/spacetimedb-bindgen",
  "crates/spacetimedb-bindings", 
  "crates/spacetimedb-macro",
  "crates/spacetimedb-cli",
  "crates/cargo-spacetime"
]
default-members = ["crates/spacetimedb-cli"]

[profile.release]
opt-level = 's'
lto = true
