[workspace]
members = [
  "crates/standalone",
  "crates/cloud",
  "crates/lib",
  "crates/core",
  "crates/bindings-sys",
  "crates/bindings",
  "crates/bench",
  "crates/bindings-macro",
  "crates/cli",
  "crates/sats",
  "crates/modules/rust-wasm-test",
  "crates/testing",
  "crates/vm",
  "crates/replay",
  "crates/client-api",
]
default-members = ["crates/cli"]

[profile.release]
opt-level = 's'
lto = true
debug = true

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
rpath = false

[profile.bench]
debug = true
