version: "3.6"

services:
  node:
    build:
      context: ./
      dockerfile: ./crates/standalone/Dockerfile
      args:
        CARGO_PROFILE: dev
    volumes:
      - ./crates/standalone:/usr/src/app/crates/standalone
      - ./crates/core:/usr/src/app/crates/core
      - ./crates/client-api:/usr/src/app/crates/client-api
      - ./crates/lib:/usr/src/app/crates/lib
      - ./crates/sats:/usr/src/app/crates/sats
      - ./crates/bindings:/usr/src/app/crates/bindings
      - ./crates/bindings-macro:/usr/src/app/crates/bindings-macro
      - ./crates/bindings-sys:/usr/src/app/crates/bindings-sys
      - ./crates/rust-wasm-test:/usr/src/app/crates/rust-wasm-test
      - /stdb
    ports:
      - "3000:80"
    # for release/non-watch mode
    entrypoint: bash -c "RUST_BACKTRACE=1 cargo watch -i flamegraphs --why -w crates/standalone -w crates/core -x 'run -p spacetimedb-standalone -- start'"
    # entrypoint: bash -c "CARGO_PROFILE_RELEASE_DEBUG=true cargo flamegraph -o my_flamegraph.svg --bin spacetimedb -c 'record -c 100 -g' -- init --worker-node"
    privileged: true
    environment:
      ENV: dev
    # Turn on core dumps, hopefully.
    ulimits:
      core:
        soft: -1
        hard: -1

  prometheus:
    build:
      context: ./packages/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./packages/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    build:
      context: ./packages/grafana
    ports:
      - "3001:3000"

