version: "3.6"

services:
  node:
    working_dir: /usr/src/app
    image: registry.digitalocean.com/clockwork/spacetimedb:latest
    volumes:
      - /stdb
    ports:
      - "3000:80"
    entrypoint: bash -c "RUST_LOG='raft=trace', CARGO_PROFILE_RELEASE_DEBUG=true CARGO_INCREMENTAL=0 RUST_BACKTRACE=1 cargo watch -i flamegraphs --why -x 'run --release -- init --worker-node'"
    # entrypoint: bash -c "CARGO_PROFILE_RELEASE_DEBUG=true cargo flamegraph -o my_flamegraph.svg --bin spacetimedb -c 'record -c 100 -g' -- init --worker-node"
    privileged: true
    environment:
      ENV: live
    # Turn on core dumps, hopefully.
    ulimits:
      core:
        soft: -1
        hard: -1
    logging:
      options:
        max-size: 1G

  prometheus:
    image: registry.digitalocean.com/clockwork/spacetimedb_prometheus:latest
    ports:
      - "9090:9090"

  grafana:
    image: registry.digitalocean.com/clockwork/spacetimedb_grafana:latest
    ports:
      - "3001:3000"

