apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stdb
  namespace: $BUILD_ENV
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data-testing
  namespace: $BUILD_ENV
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
