[package]
name = "spacetimedb"
version = "0.3.3"
edition = "2021"
license-file = "LICENSE"
description = "Easy support for interacting between SpacetimeDB and Rust."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "spacetimedb"   # The name of the target.
path = "src/lib.rs"    # The source file of the target.
# Benching off, because of https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
bench = false

[features]
default = ["macro"]
getrandom = ["spacetimedb-bindings-sys/getrandom"]
macro = ["dep:spacetimedb-bindings-macro"]

[dependencies]
spacetimedb-bindings-sys = { path = "../bindings-sys" }
spacetimedb-lib = { path = "../lib", default-features = false }
spacetimedb-bindings-macro = { path = "../bindings-macro", optional = true }
once_cell = "1.15.0"
scoped-tls = "1.0.1"
log = "0.4.17"

[dev-dependencies]
rand = "0.8.5"
bytes = "1.2.1"
