highlights:
  - name: React
    template_id: basic-react
  - name: Unity
    template_id: basic-unity
  - name: Unreal
    template_id: basic-unreal

templates:
  - id: basic-rust
    description: Bare minimum client and server using Rust with only stubs for code
    server_source: clockworklabs/SpacetimeDB/crates/cli/templates/basic-rust/server
    client_source: clockworklabs/SpacetimeDB/crates/cli/templates/basic-rust/client
    server_lang: rust
    client_lang: rust

  - id: basic-c-sharp
    description: Bare minimum client and server using C# with only stubs for code
    server_source: clockworklabs/SpacetimeDB/crates/cli/templates/basic-c-sharp/server
    client_source: clockworklabs/SpacetimeDB/crates/cli/templates/basic-c-sharp/client
    server_lang: csharp
    client_lang: csharp

  - id: basic-typescript
    description: Bare minimum client and server using TypeScript with only stubs for code
    server_source: clockworklabs/SpacetimeDB/crates/cli/templates/basic-typescript/server
    client_source: clockworklabs/SpacetimeDB/crates/cli/templates/basic-typescript/client
    server_lang: typescript
    client_lang: typescript

  - id: basic-react
    description: React web app with TypeScript server
    server_source: clockworklabs/SpacetimeDB/crates/cli/templates/basic-react/server
    client_source: clockworklabs/SpacetimeDB/crates/cli/templates/basic-react/client
    server_lang: typescript
    client_lang: typescript

  - id: basic-unity
    description: Unity game project with C# server
    server_source: clockworklabs/SpacetimeDB/crates/cli/templates/basic-unity/server
    client_source: clockworklabs/SpacetimeDB/crates/cli/templates/basic-unity/client
    server_lang: csharp
    client_lang: csharp

  - id: basic-unreal
    description: Unreal Engine project with Rust server
    server_source: clockworklabs/SpacetimeDB/crates/cli/templates/basic-unreal/server
    client_source: clockworklabs/SpacetimeDB/crates/cli/templates/basic-unreal/client
    server_lang: rust
    client_lang: none

  - id: quickstart-chat-rust
    description: Rust server/client implementing quickstart chat
    server_source: clockworklabs/SpacetimeDB/crates/cli/templates/quickstart-chat-rust/server
    client_source: clockworklabs/SpacetimeDB/crates/cli/templates/quickstart-chat-rust/client
    server_lang: rust
    client_lang: rust

  - id: quickstart-chat-c-sharp
    description: C# server/client implementing quickstart chat
    server_source: clockworklabs/SpacetimeDB/crates/cli/templates/quickstart-chat-c-sharp/server
    client_source: clockworklabs/SpacetimeDB/crates/cli/templates/quickstart-chat-c-sharp/client
    server_lang: csharp
    client_lang: csharp

  - id: quickstart-chat-typescript
    description: TypeScript server/client implementing quickstart chat
    server_source: clockworklabs/SpacetimeDB/crates/cli/templates/quickstart-chat-typescript/server
    client_source: clockworklabs/SpacetimeDB/crates/cli/templates/quickstart-chat-typescript/client
    server_lang: typescript
    client_lang: typescript

  - id: quickstart-chat-react
    description: TypeScript server with React client
    server_source: clockworklabs/SpacetimeDB/crates/cli/templates/quickstart-chat-react/server
    client_source: clockworklabs/SpacetimeDB/crates/cli/templates/quickstart-chat-react/client
    server_lang: rust
    client_lang: typescript

  - id: blackholio-unity
    description: C# server/client set up with Blackholio project
    server_source: clockworklabs/SpacetimeDB/crates/cli/templates/blackholio-unity/server
    client_source: clockworklabs/SpacetimeDB/crates/cli/templates/blackholio-unity/client
    server_lang: csharp
    client_lang: csharp

  - id: blackholio-unreal
    description: C++ server/client
    server_source: clockworklabs/SpacetimeDB/crates/cli/templates/blackholio-unreal/server
    client_source: clockworklabs/SpacetimeDB/crates/cli/templates/blackholio-unreal/client
    server_lang: rust
    client_lang: none

  - id: blackholio-unreal-blueprints
    description: C++ server with Blueprints client
    server_source: clockworklabs/SpacetimeDB/crates/cli/templates/blackholio-unreal-blueprints/server
    client_source: clockworklabs/SpacetimeDB/crates/cli/templates/blackholio-unreal-blueprints/client
    server_lang: rust
    client_lang: none
