name: Publish NuGet Package on Release

  # on:
  # release:
    # types: [published]

on:
  pull_request:
  push:
    branches:
      - '*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

        # - name: Test
        # run: dotnet test --no-build

    - name: Pack
      run: dotnet pack --no-build --output nupkgs

        # - name: Publish
      # run: dotnet nuget push nupkgs/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json

    - name: Dry Run Publish
      run: dotnet nuget push nupkgs/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols true --api-key ${{secrets.NUGET_API_KEY}} --what-if


