[package]
name = "spacetimedb-primitives"
version = "0.8.2"
edition = "2021"
license-file = "LICENSE"
description = "Primitives such as TableId and ColumnIndexAttribute"

[dependencies]
either.workspace = true
bitflags.workspace = true

[dev-dependencies]
proptest.workspace = true
