[package]
name = "spacetimedb-cli"
version = "0.1.2"
edition = "2021"
license-file = "LICENSE"
description = "A command line interface for SpacetimeDB"

[[bin]]
name = "spacetime"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.17", features = ["derive"] }
reqwest = "0.11.10"
tokio = { version = "1", features = ["full"] }
anyhow = { version = "1.0.57", features = ["backtrace"] }
serde = { version = "1.0.136" , features = ["derive"] }
serde_json = "1.0"
toml = "0.5"
dirs = "4.0"
tabled = "0.8.0"
spacetimedb-lib = { path = "../spacetimedb-lib", version = "0.2.0" }
convert_case = "0.6.0"
wasmtime = { version = "1.0.1", default-features = false, features = ["cranelift"] }
