[package]
name = "spacetimedb-cli"
version = "0.3.2"
edition = "2021"
license-file = "LICENSE"
description = "A command line interface for SpacetimeDB"

[lib]
bench = false

[[bin]]
name = "spacetime"
path = "src/main.rs"
# Benching off, because of https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.18", features = ["derive"] }
reqwest = "0.11.10"
tokio = { version = "1", features = ["full"] }
anyhow = { version = "1.0.57", features = ["backtrace"] }
serde = { version = "1.0.136" , features = ["derive"] }
serde_json = "1.0"
toml = "0.5"
dirs = "4.0"
tabled = "0.8.0"
spacetimedb-lib = { path = "../spacetimedb-lib", version = "0.3.2" }
convert_case = "0.6.0"
wasmtime = { version = "1.0.1", default-features = false, features = ["cranelift"] }
colored = "2.0.0"
duct = "0.13.5"
hex = "0.4.3"
base64 = "0.13.1"
slab = "0.4.7"
cargo_metadata = "0.15.2"
urlencoding = "2.1.2"
email_address = "0.2.4"

[dev-dependencies]
insta = { version = "1.21.0", features = ["toml"] }

[features]
tracelogging = []
