[package]
name = "spacetimedb-client-api"
version = "0.3.2"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spacetimedb-core = { version = "0.3.2", path = "../core" }
tokio = { version = "1.2", features = ["full"] }
lazy_static = "1.4.0"
spacetimedb-lib = { path = "../lib" }
log = "0.4.4"
gotham = "0.7.1"
gotham_derive = "0.7"
hyper = "0.14.18"
serde = "1.0.136"
serde_json = { version = "1.0", features = ["raw_value"] }
anyhow = { version = "1.0.57", features = ["backtrace"] }
tokio-tungstenite = "*"
regex = "1"
prometheus = "0.13.0"
email_address = "0.2.3"
tempdir = "0.3.7"
async-trait = "0.1.60"
chrono = { version = "0.4.23", features = ["serde"]}
rand = "0.8.5"
