[package]
name = "spacetimedb-slang"
version = "0.7.2"
edition = "2021"
license-file = "LICENSE"
description = "The high-level AST/Language definition"

[dependencies]
spacetimedb-lib = { path = "../lib", version = "0.7.2" }
spacetimedb-sats = { path = "../sats", version = "0.7.2" }

derive_more.workspace = true
nonempty.workspace = true
thiserror.workspace = true
