# [certificate-authority]
# jwt-priv-key-path = "~/.config/spacetime/id_ecdsas"
# jwt-pub-key-path = "~/.config/spacetime/id_ecdsa.pub"

[logs]
# The default level filter for logging
# level = "ERROR"

# directives for logging, see link for syntax:
# https://docs.rs/tracing-subscriber/latest/tracing_subscriber/struct.EnvFilter.html#directives
directives = [
    "spacetimedb=trace",
    "spacetimedb_client_api=trace",
    "spacetimedb_lib=trace",
    "spacetimedb_standalone=trace",
    "spacetimedb_commitlog=info",
    "spacetimedb_durability=info",
    "axum::rejection=trace",
]

# vim: set nowritebackup: << otherwise triggers cargo-watch
