[package]
name = "spacetimedb-lib"
version = "0.2.1"
edition = "2021"
license-file = "LICENSE"
description = "A common library for SpacetimeDB"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
custom-print = "0.1.0"
decorum = "0.3.1"
enum-as-inner = "0.5.0"
sha3 = "0.10.0"
serde = { version = "1.0.136", features = ["derive"] }
hex = "0.4.3"
thiserror = "1.0.37"

[dev-dependencies]
rand = "0.8.5"
bytes = "1.2.1"
