[package]
name = "spacetime-module"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
spacetimedb = { git = "https://github.com/ClockworkLabs/SpacetimeDB.git", rev = "595639db49d199eee136d350cb858dfc4c22c4f5" }
log = "0.4"
rand = "0.8.5"
