[package]
name = "spacetimedb-bindgen"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0"
syn = {version="1.0.57", features=["full","fold"]}
quote = "1.0.8"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.81"
convert_case = "0.5.0"
spacetimedb-bindings = { path = "../spacetimedb-bindings" }
substring = "1.4.5"
regex = "1.5.6"
parse_duration = "2.1.1"
