[package]
name = "rust-wasm-test"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html\

[lib]
crate-type = ["cdylib"]
# Benching off, because of https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
bench = false


[dependencies]
serde = { version = "1.0.136", features = ["derive"] }
spacetimedb = { path = "../spacetimedb-bindings" }
