[package]
name = "spacetimedb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "spacetimedb"   # The name of the target.
path = "src/main.rs"   # The source file of the target.
test = true            # Is tested by default.
bench = true           # Is benchmarked by default.
doc = false            # Is documented by default.
plugin = false         # Used as a compiler plugin (deprecated).
proc-macro = false     # Set to `true` for a proc-macro library.
harness = true         # Use libtest harness.
required-features = [] # Features required to build this target (N/A for lib)

[[bench]]
name = "transactional_db"
harness = false

[[bench]]
name = "object_db"
harness = false

[dependencies] 
tokio = { version = "1.2", features = ["full"] }
wasmer = "2.1.1"
wasm-bindgen = "0.2.79"
wasmer-middlewares = "2.1.1"
sha3 = "0.10.0"
hex-literal = "0.3.4"
hex = "0.4.3"
protobuf = { version = "2" }
prost = "0.6"
lazy_static = "1.4.0"
# wasmer-compiler-llvm = "2.2.1"
spacetimedb-bindings = { path = "../spacetimedb-bindings" }
log = "0.4.16"
gotham = "0.7.1"
gotham_derive = "0.7"
hyper = "0.14.18"
log4rs = { version = "1.0.0", features = ["background_rotation", "rolling_file_appender", "compound_policy", "size_trigger", "fixed_window_roller"] }
serde = "1.0.136"
serde_json = "1.0"
anyhow = { version = "1.0.57", features = ["backtrace"] }
jsonwebtoken = { version = "8.1.0" }
sha1 = "0.10.1"
base64 = "0.13.0"
tokio-tungstenite = "*"
regex = "1"
futures = "0.3"
prometheus = "0.13.0"
hostname = "^0.3"
clap = { version = "3.2.8", features = ["derive"] }
sled = "0.34.7"
email_address = "0.2.3"
int-enum = "0.4.0"
pyo3 = { version = "0.17.0"}
sqlparser = "0.21.0"
backtrace = "0.3.66"
pprof = { version = "0.10", features = ["flamegraph"] }
urlencoding = "2.1.2"
perf_monitor = "0.2"

# gluesql = "0.10"
bytes = "1.2.0" # TODO(rdaum): there's also a copy/fork of this inside prost. hmph.

# Rocksdb ostorage backend, linked only if "rocksdb" feature enabled.
[dependencies.rocksdb]
version = "0.18.0"
default-features = false
optional = true
features = ["lz4"] # if we link bzip, we get multiple defs

[features]
# Optional storage engines.
odb_rocksdb = ["dep:rocksdb"]
odb_sled = []

[dev-dependencies]
criterion = { version = "0.3", features = ["async", "async_tokio", "html_reports"] }
prost-build = { version = "0.6.1" }
tempdir = "0.3.7"
rand = "0.8.5"

[build-dependencies]
glob = "0.3.0"
prost-build = { version = "0.6.1" }
