[package]
name = "spacetimedb-bindings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wee_alloc = "0.4.5"
custom-print = "0.1.0"
enum-as-inner = "0.5.0"
sha3 = "0.10.0"
serde = "1.0.136"