[package]
name = "spacetimedb"
version = "0.2.1"
edition = "2021"
license-file = "LICENSE"
description = "Easy support for interacting between SpacetimeDB and Rust."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "spacetimedb"   # The name of the target.
path = "src/lib.rs"    # The source file of the target.
# Benching off, because of https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
bench = false

[features]
default = ["macro"]
getrandom = ["spacetimedb-bindings-sys/getrandom"]
macro = ["dep:spacetimedb-bindings-macro"]

[dependencies]
wee_alloc = "0.4.5"
custom-print = "0.1.0"
enum-as-inner = "0.5.0"
sha3 = "0.10.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = { version = "1.0.87" }
hex = "0.4.3"
spacetimedb-bindings-sys = { path = "../spacetimedb-bindings-sys", version = "0.2.2" }
spacetimedb-lib = { path = "../spacetimedb-lib", version = "0.2.2" }
spacetimedb-bindings-macro = { path = "../spacetimedb-bindings-macro", version = "0.2.2", optional = true }
once_cell = "1.15.0"

[dev-dependencies]
rand = "0.8.5"
bytes = "1.2.1"
