# Merely starts docker containers for the application then immediately brings them down.
# Later iterations should run some integration tests.
name: Docker Compose Actions Workflow
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start containers
        run: docker compose up -d
      - name: Run smoketests
        run: test/run-smoke-tests.sh -x bitcraftmini-pretest
      - name: Stop containers
        if: success() || failure()
        run: docker compose down
