on: [pull_request]

name: Wasm bindings

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with: { targets: wasm32-unknown-unknown }

      - name: Build rust-wasm-test
        run: cargo build -p rust-wasm-test --release --target wasm32-unknown-unknown

      - name: Run bindgen tests
        run: cargo test -p spacetimedb-cli
